name: wemolo_challenge
description: "Wemolo"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  provider: ^6.1.2
  flutter_card_swiper: ^7.0.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  mockito: ^5.4.4


flutter:

  uses-material-design: true

  fonts:
    - family: AlbertSans
      fonts:
        - asset: fonts/AlbertSans-Regular.ttf
        - asset: fonts/AlbertSans-Bold.ttf
          weight: 700

